# Generated by Django 5.2.6 on 2025-11-05 01:06

import django.db.models.deletion
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'custom_user',
                'indexes': [models.Index(fields=['username'], name='custom_user_usernam_674d82_idx'), models.Index(fields=['email'], name='custom_user_email_55dec9_idx'), models.Index(fields=['created_at'], name='custom_user_created_3135d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(default=stories.models.generate_short_uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('flow', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('nlp_analysis', models.JSONField(blank=True, default=dict)),
                ('users_data', models.JSONField(blank=True, default=list)),
                ('features_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='stories.customuser')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='GenerationSession',
            fields=[
                ('session_id', models.CharField(default=stories.models.generate_short_uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('llm_model_used', models.CharField(default='ibm-granite/granite-3.3-8b-instruct', max_length=100)),
                ('user_stories_generated', models.IntegerField(default=0)),
                ('wireframes_generated', models.IntegerField(default=0)),
                ('scenarios_generated', models.IntegerField(default=0)),
                ('total_iterations', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_sessions', to='stories.customuser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stories.project')),
            ],
            options={
                'db_table': 'generation_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('export_id', models.CharField(default=stories.models.generate_short_uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('export_format', models.CharField(choices=[('html', 'HTML Documentation'), ('pdf', 'PDF Document'), ('word', 'Word Document'), ('json', 'JSON Data'), ('zip', 'Complete Package (ZIP)')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('include_stories', models.BooleanField(default=True)),
                ('include_wireframes', models.BooleanField(default=True)),
                ('include_scenarios', models.BooleanField(default=True)),
                ('export_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='stories.customuser')),
                ('generation_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.generationsession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='stories.project')),
            ],
            options={
                'db_table': 'exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('story_id', models.CharField(default=stories.models.generate_short_uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('story_text', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('benefit', models.TextField()),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('story_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('implemented', 'Implemented')], default='draft', max_length=20)),
                ('generated_by_llm', models.BooleanField(default=True)),
                ('iteration', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='stories.project')),
            ],
            options={
                'db_table': 'user_stories',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.CharField(default=stories.models.generate_short_uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('scenario_text', models.TextField()),
                ('scenario_type', models.CharField(choices=[('happy_path', 'Happy Path'), ('alternate_path', 'Alternate Path'), ('exception_path', 'Exception Path'), ('boundary_case', 'Boundary Case')], default='happy_path', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('detected_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('has_proper_structure', models.BooleanField(default=True)),
                ('gherkin_steps', models.JSONField(blank=True, default=list)),
                ('enhanced_with_llm', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('tested', 'Tested')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='stories.project')),
                ('user_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='stories.userstory')),
            ],
            options={
                'db_table': 'scenarios',
                'ordering': ['user_story', 'scenario_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wireframe',
            fields=[
                ('wireframe_id', models.CharField(default=stories.models.generate_short_uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('page_name', models.CharField(max_length=255)),
                ('page_type', models.CharField(choices=[('login', 'Login Page'), ('dashboard', 'Dashboard'), ('profile', 'User Profile'), ('products', 'Product Listing'), ('cart', 'Shopping Cart'), ('checkout', 'Checkout Page'), ('search', 'Search Results'), ('admin', 'Admin Panel'), ('general', 'General Page')], default='general', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('creole_content', models.TextField(blank=True, null=True)),
                ('salt_diagram', models.TextField(blank=True, null=True)),
                ('generated_with_rag', models.BooleanField(default=True)),
                ('wireframe_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireframes', to='stories.project')),
            ],
            options={
                'db_table': 'wireframes',
                'ordering': ['page_name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('history_id', models.CharField(default=stories.models.generate_short_uuid, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(choices=[('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('stories_generated', 'User Stories Generated'), ('wireframes_generated', 'Wireframes Generated'), ('scenarios_generated', 'Scenarios Generated'), ('export_created', 'Export Created'), ('review_iteration', 'Review Iteration')], max_length=50)),
                ('action_details', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('generation_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.generationsession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='stories.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activities', to='stories.customuser')),
                ('related_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.scenario')),
                ('related_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.userstory')),
                ('related_wireframe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.wireframe')),
            ],
            options={
                'db_table': 'project_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='projects_user_id_05c680_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_date'], name='projects_created_131144_idx'),
        ),
        migrations.AddIndex(
            model_name='generationsession',
            index=models.Index(fields=['project', 'status'], name='generation__project_6d53af_idx'),
        ),
        migrations.AddIndex(
            model_name='generationsession',
            index=models.Index(fields=['user', 'start_time'], name='generation__user_id_ec7aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['project', 'export_format'], name='exports_project_1ad3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['user', 'exported_at'], name='exports_user_id_e952de_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['project', 'status'], name='user_storie_project_c64305_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['project', 'priority'], name='user_storie_project_b2aa57_idx'),
        ),
        migrations.AddIndex(
            model_name='userstory',
            index=models.Index(fields=['feature'], name='user_storie_feature_e30e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['user_story', 'scenario_type'], name='scenarios_user_st_6a3c07_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['project', 'status'], name='scenarios_project_8d7fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='wireframe',
            index=models.Index(fields=['project', 'page_type'], name='wireframes_project_c7bc69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wireframe',
            unique_together={('project', 'page_name', 'version')},
        ),
        migrations.AddIndex(
            model_name='projecthistory',
            index=models.Index(fields=['project', 'action_type'], name='project_his_project_7d2fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthistory',
            index=models.Index(fields=['project', 'timestamp'], name='project_his_project_7d5186_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthistory',
            index=models.Index(fields=['user', 'timestamp'], name='project_his_user_id_bb64e1_idx'),
        ),
    ]
