# Generated by Django 5.2.7 on 2025-11-28 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('individual', 'Individual Users'), ('advisors', 'Financial Advisors'), ('managers', 'Investment Managers'), ('admins', 'Administrators')], max_length=20)),
                ('stories', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_story_groups', to='stories.project')),
            ],
            options={
                'db_table': 'user_story_groups',
                'ordering': ['role'],
                'indexes': [models.Index(fields=['project', 'role'], name='user_story__project_81e7dc_idx')],
                'unique_together': {('project', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserStoryPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_story_page', to='stories.project')),
            ],
            options={
                'db_table': 'user_story_pages',
                'indexes': [models.Index(fields=['project', 'is_accepted'], name='user_story__project_75c5f2_idx'), models.Index(fields=['created_at'], name='user_story__created_5a9624_idx')],
            },
        ),
    ]
