# Generated by Django 5.2.7 on 2025-12-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_userstorygroup_userstorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireframe',
            name='features_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wireframe',
            name='stories_count',
            field=models.IntegerField(default=0),
        ),
    ]
