# Generated by Django 5.2.7 on 2025-12-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_wireframe_features_count_wireframe_stories_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireframe',
            name='generated_at',
            field=models.DateTimeField(blank=True, help_text='When this wireframe was generated', null=True),
        ),
        migrations.AddField(
            model_name='wireframe',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Whether this wireframe was created locally (not from database)'),
        ),
        migrations.AlterField(
            model_name='wireframe',
            name='generated_with_rag',
            field=models.BooleanField(default=False, help_text='Whether this wireframe was generated using RAG'),
        ),
    ]
